### ISSUE TITLE
Create Data Models for POST/PATCH Endpoints

### ISSUE THREAD

**Issue by oliv10** [Shield-Cyber/OpenVAS-REST-API#165]
# Credential

- [x] /credential/clone/credential
- [x] /credential/create/credential
- [x] /credential/modify/credential

# Port

- [x] /port/clone/port/list
- [x] /port/create/port/list
- [x] /port/create/port/range
- [x] /port/modify/port/list

# Report

- [x] /report/clone/report/formats
- [x] /report/import/report
- [x] /report/import/report/format
- [x] /report/modify/report/format

# Target

- [x] /target/clone/target
- [x] /target/clone/target
- [x] /target/modify/target

# Task

- [x] /task/clone/task
- [x] /task/create/task
- [x] /task/modify/task
- [x] /task/move/task
- [x] /task/resume/task - _/endpoint/resume/UUID_
- [x] /task/start/task - _/endpoint/start/UUID_
- [x] /task/stop/task - _/endpoint/stop/UUID_

## All _clone_ endpoints will be in the format of _/endpoint/clone/UUID_.

**Comment by oliv10** [comment]
All completed in dev branch.
